server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:jobdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
rabbitmq:
  host: localhost
  port: 5672
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info, prometheus
